### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by aminnoorani** [DeplanckeLab/ChromatinHD#5]
Hello,

Once I install the library through pip, I get the error below. I use Python3.8 on conda:

import chromatinhd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/chromatinhd/__init__.py", line 9, in <module>
    from . import loaders
  File "/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/chromatinhd/loaders/__init__.py", line 1, in <module>
    from .pool import LoaderPool, LoaderPool2
  File "/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/chromatinhd/loaders/pool.py", line 30, in <module>
    class LoaderPool:
  File "/opt/anaconda3/envs/scenicplus/lib/python3.8/site-packages/chromatinhd/loaders/pool.py", line 34, in LoaderPool
    n_todo: list[int]
TypeError: 'type' object is not subscriptable

Thanks

**Comment by zouter** [comment]
Hi
Thank you for trying out the package. The error you got was because of some python 3.9+ specific syntax. I replaced that now so that it should work with python 3.8. Could you try to upgrade to v0.0.19 and check if it was fixed?

**Comment by zouter** [comment]
That error likely indicates something went wrong with compiling the cython code. I created an updated version which might resolve this, could you try to install version 0.0.20 and see if it is resolved?
